name: Start commiter

on:
  workflow_dispatch:
  schedule:
    # Runs at 2am UTC
    - cron: "0 3 * * *"
jobs:
  run-commiter:
    name: Update Github with commits
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1
      - name: Setup git user
        run: |
            git config --global user.name "himaster"
            git config --global user.email "vitalibicov83@gmail.com"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i moment
      - name: run commiter
        env:
          FORCE_REMOVE: "y"
          COMMIT_MODE: "random"
          GITHUB_USERNAME: "himaster"
          GITHUB_REPO: "charts"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          START_DATE: 1
          END_DATE: 1
          MAX_COMMIT_NUMBER: 20
          RATIO_monday: 0.8
          PROBABILITY_monday: 0.6
          RATIO_tuesday: 0.9
          PROBABILITY_tuesday: 0.8
          RATIO_wednesday: 0.9
          PROBABILITY_wednesday: 0.8
          RATIO_thursday: 0.9
          PROBABILITY_thursday: 0.8
          RATIO_friday: 0.7
          PROBABILITY_friday: 0.8
          RATIO_saturday: 0.5
          PROBABILITY_saturday: 0.5
          RATIO_sunday: 0
          PROBABILITY_sunday: 0
        run: node commiter.js

